name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --shamefully-hoist
          npx playwright install

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Run tests
        run: pnpm test

      - name: Run type tests
        run: pnpm test:type
