name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm exec playwright-core install

      - name: Prepare is needed, because it generate types
        run: pnpm dev:prepare

      - name: Run tests
        run: pnpm vitest run --dir ./test

      - name: Run type tests
        run: pnpm vitest --dir ./test --typecheck.only --typecheck.ignoreSourceErrors
